//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bildwahl.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bildwahl.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Customers ähnelt.
        /// </summary>
        public static string AllCustomersViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllCustomersViewModel_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Customers ähnelt.
        /// </summary>
        public static string TobiiTestViewModel_DisplayName
        {
            get
            {
                return ResourceManager.GetString("TobiiTestViewModel_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companies have no last name ähnelt.
        /// </summary>
        public static string Customer_Error_CompanyHasNoLastName {
            get {
                return ResourceManager.GetString("Customer_Error_CompanyHasNoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address is invalid ähnelt.
        /// </summary>
        public static string Customer_Error_InvalidEmail {
            get {
                return ResourceManager.GetString("Customer_Error_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail address is missing ähnelt.
        /// </summary>
        public static string Customer_Error_MissingEmail {
            get {
                return ResourceManager.GetString("Customer_Error_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name is missing ähnelt.
        /// </summary>
        public static string Customer_Error_MissingFirstName {
            get {
                return ResourceManager.GetString("Customer_Error_MissingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name is missing ähnelt.
        /// </summary>
        public static string Customer_Error_MissingLastName {
            get {
                return ResourceManager.GetString("Customer_Error_MissingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company ähnelt.
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_Company {
            get {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Not Specified) ähnelt.
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_NotSpecified {
            get {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person ähnelt.
        /// </summary>
        public static string CustomerViewModel_CustomerTypeOption_Person {
            get {
                return ResourceManager.GetString("CustomerViewModel_CustomerTypeOption_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Customer ähnelt.
        /// </summary>
        public static string CustomerViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CustomerViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer type must be selected ähnelt.
        /// </summary>
        public static string CustomerViewModel_Error_MissingCustomerType {
            get {
                return ResourceManager.GetString("CustomerViewModel_Error_MissingCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot save an invalid customer. ähnelt.
        /// </summary>
        public static string CustomerViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("CustomerViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new customer ähnelt.
        /// </summary>
        public static string MainWindowViewModel_Command_CreateNewCustomer {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View all customers ähnelt.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllCustomers {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MVVM Demo App ähnelt.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
